services:
  vpn-bot:
    build: .
    env_file: app/.env
    volumes:
      - ./data:/app/app/data
    restart: unless-stopped

  vpn-bot-test:
    profiles: ["test"]
    build: .
    env_file: app/.env.test
    volumes:
      - ./data-test:/app/app/data
    restart: unless-stopped
